export const informacoes = [
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 2",
        lojas: "Loja 2",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Sim",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Job Reaberto",
        lojas: "Loja 3",
        usuario: "Tahti Tatiyuwa",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Job Reaberto",
        lojas: "Loja 4",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Notificação",
        lojas: "Loja 5",
        usuario: "Gustavo Pontes",
        data: "05/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado 6",
        lojas: "Loja 6",
        usuario: "Lojista Teste",
        data: "27/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Notificação",
        lojas: "Loja 7",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 8",
        lojas: "Loja 8",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 9",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 10",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 11",
        lojas: "Loja 11",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 12",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 13",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 14",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 15",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 16",
        usuario: "Lojista Teste",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Job Reaberto",
        lojas: "Loja 17",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 18",
        lojas: "Loja 18",
        usuario: "Malltec",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Job Reaberto",
        lojas: "Loja 19",
        usuario: "Tathiana Imuta",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 20",
        usuario: "Miniatura Lojista",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado",
        lojas: "Loja 21",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Job Reaberto",
        lojas: "Loja 22",
        usuario: "Eduardo Ashikawa",
        data: "12/03/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
]