export const informacoes = [
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
]