export const informacoes = [
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 2",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 3",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 1",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 2",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 3",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 4",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 5",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 6",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 7",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 8",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
    {
        titulo: "Comunicado teste 9",
        lojas: "Loja 1",
        usuario: "Gustavo Pontes",
        data: "07/12/2022",
        termosECondicoes: "Não",
        enviados: 1,
        lidos: 1,
        pendentes: 0,
        recebidosSemLeitura: 0
    },
]